import { NextResponse } from 'next/server';

/**
 * RFC 9457 Problem Details for HTTP APIs (supersedes RFC 7807).
 * Standardized machine-readable error payload format for EasyConvert REST APIs.
 */
export interface ProblemDetails {
  /**
   * A URI reference that identifies the problem type.
   */
  type: string;
  /**
   * A short, human-readable summary of the problem type.
   */
  title: string;
  /**
   * The HTTP status code generated by the origin server for this occurrence of the problem.
   */
  status: number;
  /**
   * A human-readable explanation specific to this occurrence of the problem.
   */
  detail: string;
  /**
   * A URI reference that identifies the specific occurrence of the problem.
   */
  instance: string;
  /**
   * Optional list of invalid parameters for validation failures.
   */
  invalidParams?: Array<{ name: string; reason: string }>;
  /**
   * Backward-compatibility flag for legacy clients.
   */
  success: false;
  /**
   * Backward-compatibility error message mirroring detail.
   */
  error: string;
  [key: string]: unknown;
}

const DEFAULT_PROBLEM_TYPES: Record<number, { type: string; title: string }> = {
  400: {
    type: 'https://api.easyconvert.io/problems/bad-request',
    title: 'Bad Request',
  },
  401: {
    type: 'https://api.easyconvert.io/problems/unauthorized',
    title: 'Unauthorized',
  },
  403: {
    type: 'https://api.easyconvert.io/problems/forbidden',
    title: 'Forbidden',
  },
  404: {
    type: 'https://api.easyconvert.io/problems/not-found',
    title: 'Not Found',
  },
  405: {
    type: 'https://api.easyconvert.io/problems/method-not-allowed',
    title: 'Method Not Allowed',
  },
  413: {
    type: 'https://api.easyconvert.io/problems/payload-too-large',
    title: 'Payload Too Large',
  },
  415: {
    type: 'https://api.easyconvert.io/problems/unsupported-media-type',
    title: 'Unsupported Media Type',
  },
  422: {
    type: 'https://api.easyconvert.io/problems/unprocessable-entity',
    title: 'Unprocessable Entity',
  },
  429: {
    type: 'https://api.easyconvert.io/problems/quota-exceeded',
    title: 'Too Many Requests',
  },
  500: {
    type: 'https://api.easyconvert.io/problems/internal-server-error',
    title: 'Internal Server Error',
  },
  503: {
    type: 'https://api.easyconvert.io/problems/service-unavailable',
    title: 'Service Unavailable',
  },
};

/**
 * Formats and returns an RFC 9457 compliant problem details JSON response with Content-Type: application/problem+json.
 */
export function createProblemDetailsResponse(
  status: number,
  detail: string,
  instance: string = '/api/v1/convert',
  customTitle?: string,
  customType?: string,
  extraHeaders?: Record<string, string>,
  invalidParams?: Array<{ name: string; reason: string }>
): NextResponse {
  const fallback = DEFAULT_PROBLEM_TYPES[status] || {
    type: 'about:blank',
    title: status >= 500 ? 'Internal Error' : 'Request Error',
  };

  const payload: ProblemDetails = {
    type: customType || fallback.type,
    title: customTitle || fallback.title,
    status,
    detail,
    instance,
    success: false,
    error: detail,
    ...(invalidParams && invalidParams.length > 0 ? { invalidParams } : {}),
  };

  return NextResponse.json(payload, {
    status,
    headers: {
      'Content-Type': 'application/problem+json',
      ...extraHeaders,
    },
  });
}
