import { NextResponse } from 'next/server';
import type { EngineUnavailableError, PdfAValidationError } from '../types';

/**
 * RFC 9457 Problem Details for HTTP APIs (supersedes RFC 7807).
 * Standardized machine-readable error payload format for EasyConvert REST APIs.
 */
export interface ProblemDetails {
  /**
   * A URI reference that identifies the problem type.
   */
  type: string;
  /**
   * A short, human-readable summary of the problem type.
   */
  title: string;
  /**
   * The HTTP status code generated by the origin server for this occurrence of the problem.
   */
  status: number;
  /**
   * A human-readable explanation specific to this occurrence of the problem.
   */
  detail: string;
  /**
   * A URI reference that identifies the specific occurrence of the problem.
   */
  instance: string;
  /**
   * Optional list of invalid parameters for validation failures.
   */
  invalidParams?: Array<{ name: string; reason: string }>;
  /**
   * Backward-compatibility flag for legacy clients.
   */
  success: false;
  /**
   * Backward-compatibility error message mirroring detail.
   */
  error: string;
  [key: string]: unknown;
}

const DEFAULT_PROBLEM_TYPES: Record<number, { type: string; title: string }> = {
  400: {
    type: 'https://api.easyconvert.io/problems/bad-request',
    title: 'Bad Request',
  },
  401: {
    type: 'https://api.easyconvert.io/problems/unauthorized',
    title: 'Unauthorized',
  },
  403: {
    type: 'https://api.easyconvert.io/problems/forbidden',
    title: 'Forbidden',
  },
  404: {
    type: 'https://api.easyconvert.io/problems/not-found',
    title: 'Not Found',
  },
  405: {
    type: 'https://api.easyconvert.io/problems/method-not-allowed',
    title: 'Method Not Allowed',
  },
  413: {
    type: 'https://api.easyconvert.io/problems/payload-too-large',
    title: 'Payload Too Large',
  },
  415: {
    type: 'https://api.easyconvert.io/problems/unsupported-media-type',
    title: 'Unsupported Media Type',
  },
  422: {
    type: 'https://api.easyconvert.io/problems/unprocessable-entity',
    title: 'Unprocessable Entity',
  },
  429: {
    type: 'https://api.easyconvert.io/problems/quota-exceeded',
    title: 'Too Many Requests',
  },
  500: {
    type: 'https://api.easyconvert.io/problems/internal-server-error',
    title: 'Internal Server Error',
  },
  503: {
    type: 'https://api.easyconvert.io/problems/service-unavailable',
    title: 'Service Unavailable',
  },
};

/** Problem type for a conversion whose native engine (for example LibreOffice) is not installed. */
export const ENGINE_UNAVAILABLE_PROBLEM_TYPE = 'https://api.easyconvert.io/problems/engine-unavailable';
const HTTP_SERVICE_UNAVAILABLE = 503;
const HTTP_UNPROCESSABLE_ENTITY = 422;

/** Problem type for a PDF/A output that veraPDF rejected. */
export const PDFA_VALIDATION_PROBLEM_TYPE = 'https://api.easyconvert.io/problems/pdfa-validation-failed';

/** Problem type for a short-lived per-key burst rejection (retry after seconds), distinct from the daily quota. */
export const RATE_LIMITED_PROBLEM_TYPE = 'https://api.easyconvert.io/problems/rate-limited';

/**
 * Formats and returns an RFC 9457 compliant problem details JSON response with Content-Type: application/problem+json.
 */
export function createProblemDetailsResponse(
  status: number,
  detail: string,
  instance: string = '/api/v1/convert',
  customTitle?: string,
  customType?: string,
  extraHeaders?: Record<string, string>,
  invalidParams?: Array<{ name: string; reason: string }>,
  extensions?: Record<string, unknown>
): NextResponse {
  const fallback = DEFAULT_PROBLEM_TYPES[status] || {
    type: 'about:blank',
    title: status >= 500 ? 'Internal Error' : 'Request Error',
  };

  const payload: ProblemDetails = {
    type: customType || fallback.type,
    title: customTitle || fallback.title,
    status,
    detail,
    instance,
    success: false,
    error: detail,
    ...(invalidParams && invalidParams.length > 0 ? { invalidParams } : {}),
    ...extensions,
  };

  return NextResponse.json(payload, {
    status,
    headers: {
      'Content-Type': 'application/problem+json',
      ...extraHeaders,
    },
  });
}

/**
 * Maps an EngineUnavailableError to HTTP 503: the pair is supported, but the native engine it
 * needs is not installed on this deployment.
 */
export function createEngineUnavailableResponse(
  error: EngineUnavailableError,
  instance: string,
  extraHeaders?: Record<string, string>
): NextResponse {
  return createProblemDetailsResponse(
    HTTP_SERVICE_UNAVAILABLE,
    error.message,
    instance,
    'Engine Unavailable',
    ENGINE_UNAVAILABLE_PROBLEM_TYPE,
    extraHeaders
  );
}

/**
 * Maps a PdfAValidationError to HTTP 422: the document converted, but the PDF/A output does not
 * conform. `profile` is the requested level and `failedRules` the veraPDF rule IDs that failed.
 */
export function createPdfaValidationResponse(
  error: PdfAValidationError,
  instance: string,
  extraHeaders?: Record<string, string>
): NextResponse {
  return createProblemDetailsResponse(
    HTTP_UNPROCESSABLE_ENTITY,
    error.message,
    instance,
    'PDF/A Validation Failed',
    PDFA_VALIDATION_PROBLEM_TYPE,
    extraHeaders,
    undefined,
    { profile: error.profile, failedRules: [...error.failedRules] }
  );
}
