/**
 * Namespaces of storage keys. Every key is generated by the server; callers never choose one.
 * - `uploads/...`: multipart uploads used as job inputs. They have no owner and are reachable by
 *   anyone holding the key (capability semantics).
 * - `conversions/<userId>/...`: synchronous API outputs owned by that user.
 * - `results/<jobId>/...`: queue job outputs, owned by the job's user when the job has one.
 */
export type StorageKeyNamespace =
  | { namespace: 'upload' }
  | { namespace: 'user-conversion'; userId: string }
  | { namespace: 'job-result'; jobId: string }
  | { namespace: 'other' };

const UPLOAD_KEY_PREFIX = 'uploads/';
const USER_CONVERSION_KEY_PATTERN = /^conversions\/([^/]+)\//;
const JOB_RESULT_KEY_PATTERN = /^results\/([^/]+)\//;

/** Whether a key is in the ownerless multipart upload namespace. */
export function isUploadKey(key: string): boolean {
  return key.startsWith(UPLOAD_KEY_PREFIX);
}

export function classifyStorageKey(key: string): StorageKeyNamespace {
  if (isUploadKey(key)) {
    return { namespace: 'upload' };
  }

  const userConversion = USER_CONVERSION_KEY_PATTERN.exec(key);
  if (userConversion) {
    return { namespace: 'user-conversion', userId: userConversion[1] };
  }

  const jobResult = JOB_RESULT_KEY_PATTERN.exec(key);
  if (jobResult) {
    return { namespace: 'job-result', jobId: jobResult[1] };
  }

  return { namespace: 'other' };
}
