export const ARCHIVE_SECURITY_LIMITS = {
  MAX_FILES: 1000,
  MAX_UNCOMPRESSED_SIZE: 500 * 1024 * 1024,
  MAX_RATIO: 100,
};

export const MAX_FILES = ARCHIVE_SECURITY_LIMITS.MAX_FILES;
export const MAX_UNCOMPRESSED_SIZE = ARCHIVE_SECURITY_LIMITS.MAX_UNCOMPRESSED_SIZE;
export const MAX_RATIO = ARCHIVE_SECURITY_LIMITS.MAX_RATIO;
