import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import JSZip from 'jszip';
import { ARCHIVE_SECURITY_LIMITS } from '../src/lib/conversions/archive';
import { extractArchiveContained, parse7zTechnicalListing, stripSevenZipPasswordPrompt } from '../src/lib/conversions/archive-extraction-safety';
import { convertWithNative7z } from '../src/worker/engines';
import { getOracleToolPath } from './helpers/differential-oracle';
import { oracleTest } from './helpers/oracle-test';

/**
 * Proves the `7z l -slt` key whitelist (archive-extraction-safety.ts) against real files of every archive
 * source the registry offers that 7-Zip reads: ISO, CAB, ARJ, RPM, DEB, CPIO, DMG, IMG, LZMA and Z, plus
 * LZH, WIM, CHM, SquashFS, VHD, MSI and NSIS. Each fixture under tests/fixtures/archive-sources was built by a
 * tool other than 7-Zip (see PROVENANCE there), so a key 7-Zip prints for a genuine file but the whitelist
 * does not know would turn a valid upload into a malformed-listing rejection. The expected bytes come from
 * the fixtures' known payload, never from the extraction under test.
 */

const FIXTURE_DIR = path.resolve(__dirname, 'fixtures', 'archive-sources');
const EXTRACT_TIMEOUT_MS = 60_000;
const SLOW_TEST_TIMEOUT_MS = 120_000;
const BYTE_VALUES = 256;
const LONG_TEXT_LINES = 400;
const EL_TORITO_IMAGE_BYTES = 2048;
const SECTOR_BYTES = 512;
const ISO_DESCRIPTOR_OFFSET = 0x8001;
const AR_GLOBAL_HEADER = '!<arch>\n';
const AR_MEMBER_HEADER_BYTES = 60;
const AR_MEMBER_NAME_BYTES = 16;
const AR_MEMBER_SIZE_OFFSET = 48;
const AR_MEMBER_SIZE_BYTES = 10;

const HELLO = Buffer.from('hello archive\n', 'utf-8');
const NESTED = Buffer.from('nested file\n', 'utf-8');
const DATA_BIN = Buffer.from(Array.from({ length: BYTE_VALUES }, (_unused, index) => index));
const LONG_TEXT = Buffer.from(
  Array.from({ length: LONG_TEXT_LINES }, (_unused, index) => `line ${String(index).padStart(4, '0')} of the archive probe payload\n`).join(''),
  'utf-8'
);
const SOURCE_TREE: Readonly<Record<string, Buffer>> = {
  'hello.txt': HELLO,
  'dir/nested.txt': NESTED,
  'dir/data.bin': DATA_BIN,
};

function readFixture(name: string): Buffer {
  return fs.readFileSync(path.join(FIXTURE_DIR, name));
}

/** Minimal ar(1) reader, independent of 7-Zip: the expected members of a .deb. */
function readArMember(archive: Buffer, memberName: string): Buffer {
  expect(archive.subarray(0, AR_GLOBAL_HEADER.length).toString('latin1')).toBe(AR_GLOBAL_HEADER);
  let offset = AR_GLOBAL_HEADER.length;
  while (offset + AR_MEMBER_HEADER_BYTES <= archive.length) {
    const name = archive.toString('latin1', offset, offset + AR_MEMBER_NAME_BYTES).trim().replace(/\/$/, '');
    const size = Number(archive.toString('latin1', offset + AR_MEMBER_SIZE_OFFSET, offset + AR_MEMBER_SIZE_OFFSET + AR_MEMBER_SIZE_BYTES).trim());
    const start = offset + AR_MEMBER_HEADER_BYTES;
    if (name === memberName) return archive.subarray(start, start + size);
    offset = start + size + (size % 2);
  }
  throw new Error(`ar member ${memberName} not found`);
}

interface Magic {
  /** Negative offsets count from the end of the file. */
  offset: number;
  bytes: Buffer;
}

function magic(offset: number, text: string | number[]): Magic {
  return { offset, bytes: typeof text === 'string' ? Buffer.from(text, 'latin1') : Buffer.from(text) };
}

interface SourceFixture {
  file: string;
  /** The registry source format (or the worker-only format) this file stands for. */
  format: string;
  /** Format-defining bytes proving the fixture is the claimed container, not renamed data. */
  magic: Magic[];
  /** Files the extraction must produce, byte for byte, keyed by forward-slash path. */
  expected: () => Record<string, Buffer>;
  /** When true the extraction must produce exactly the expected files and nothing else. */
  exact: boolean;
  /** Directory entries the listing carries (an empty volume still lists its root). */
  expectedEntryCount?: number;
  /** Source format id the worker route accepts for this container, when it extracts it. */
  workerFormat?: string;
}

const FIXTURES: SourceFixture[] = [
  {
    file: 'joliet-rockridge.iso',
    format: 'iso',
    magic: [magic(ISO_DESCRIPTOR_OFFSET, 'CD001')],
    expected: () => ({ ...SOURCE_TREE }),
    exact: true,
    workerFormat: 'iso',
  },
  {
    file: 'udf.iso',
    format: 'iso',
    magic: [magic(ISO_DESCRIPTOR_OFFSET, 'CD001')],
    expected: () => ({ ...SOURCE_TREE }),
    exact: true,
    workerFormat: 'iso',
  },
  {
    file: 'bootable.iso',
    format: 'iso',
    magic: [magic(ISO_DESCRIPTOR_OFFSET, 'CD001')],
    // boot.cat is generated by the mastering tool; the El Torito image is zero-filled.
    expected: () => ({
      'hello.txt': HELLO,
      'boot.img': Buffer.alloc(EL_TORITO_IMAGE_BYTES),
      '[BOOT]/Boot-NoEmul.img': Buffer.alloc(EL_TORITO_IMAGE_BYTES),
    }),
    exact: false,
    workerFormat: 'iso',
  },
  {
    file: 'probe.cab',
    format: 'cab',
    magic: [magic(0, 'MSCF')],
    expected: () => ({ ...SOURCE_TREE }),
    exact: true,
    workerFormat: 'cab',
  },
  {
    file: 'probe.arj',
    format: 'arj',
    magic: [magic(0, [0x60, 0xea])],
    expected: () => ({ ...SOURCE_TREE }),
    exact: true,
    workerFormat: 'arj',
  },
  {
    file: 'probe.lzh',
    format: 'lzh',
    magic: [magic(2, '-lh0-')],
    expected: () => ({ ...SOURCE_TREE }),
    exact: true,
    workerFormat: 'lzh',
  },
  {
    file: 'probe.rpm',
    format: 'rpm',
    magic: [magic(0, [0xed, 0xab, 0xee, 0xdb])],
    // 7-Zip hands out the payload cpio; rpm2cpio produced the expected bytes.
    expected: () => ({ 'probe-1.0-1.noarch.cpio': readFixture('probe.rpm.payload.cpio') }),
    exact: true,
    workerFormat: 'rpm',
  },
  {
    file: 'probe.deb',
    format: 'deb',
    magic: [magic(0, AR_GLOBAL_HEADER)],
    expected: () => {
      const deb = readFixture('probe.deb');
      return { 'control.tar': readArMember(deb, 'control.tar'), 'data.tar': readArMember(deb, 'data.tar') };
    },
    exact: true,
    workerFormat: 'deb',
  },
  {
    file: 'probe.wim',
    format: 'wim',
    magic: [magic(0, 'MSWIM\0\0\0')],
    expected: () => ({ ...SOURCE_TREE }),
    exact: true,
    workerFormat: 'wim',
  },
  {
    file: 'newc.cpio',
    format: 'cpio',
    magic: [magic(0, '070701')],
    expected: () => ({ ...SOURCE_TREE }),
    exact: true,
    workerFormat: 'cpio',
  },
  {
    file: 'odc.cpio',
    format: 'cpio',
    magic: [magic(0, '070707')],
    expected: () => ({ ...SOURCE_TREE }),
    exact: true,
    workerFormat: 'cpio',
  },
  {
    // A UDIF image of an Apple partition map and an empty HFS+ volume (no HFS+ writer is available to fill it):
    // the proof is that the volume listing, with its HFS-specific keys, is accepted and the root extracts.
    file: 'probe.dmg',
    format: 'dmg',
    magic: [magic(-SECTOR_BYTES, 'koly')],
    expected: () => ({}),
    exact: true,
    expectedEntryCount: 1,
  },
  {
    file: 'empty-hfsplus.img',
    format: 'img',
    magic: [magic(1024, 'H+')],
    expected: () => ({}),
    exact: true,
    expectedEntryCount: 1,
  },
  {
    file: 'probe-ext4.img',
    format: 'img',
    magic: [magic(1080, [0x53, 0xef])],
    expected: () => ({ ...SOURCE_TREE }),
    exact: true,
  },
  {
    file: 'probe-fat.img',
    format: 'img',
    magic: [magic(54, 'FAT12'), magic(510, [0x55, 0xaa])],
    expected: () => ({ ...SOURCE_TREE }),
    exact: true,
  },
  {
    file: 'probe.vhd',
    format: 'vhd',
    magic: [magic(-SECTOR_BYTES, 'conectix')],
    expected: () => ({ ...SOURCE_TREE }),
    exact: true,
  },
  {
    file: 'probe.chm',
    format: 'chm',
    magic: [magic(0, 'ITSF')],
    expected: () => ({ ...SOURCE_TREE }),
    exact: true,
  },
  {
    file: 'probe.squashfs',
    format: 'squashfs',
    magic: [magic(0, 'hsqs')],
    expected: () => ({ ...SOURCE_TREE }),
    exact: true,
  },
  {
    // The MSI also holds database tables as streams; only the two payload streams are compared.
    file: 'probe.msi',
    format: 'msi',
    magic: [magic(0, [0xd0, 0xcf, 0x11, 0xe0, 0xa1, 0xb1, 0x1a, 0xe1])],
    expected: () => ({ 'hello.txt': HELLO, 'data.bin': DATA_BIN }),
    exact: false,
  },
  {
    file: 'probe-nsis.exe',
    format: 'nsis',
    magic: [magic(0, 'MZ')],
    expected: () => ({
      '$TEMP/probe/hello.txt': HELLO,
      '$TEMP/probe/dir/nested.txt': NESTED,
      '$TEMP/probe/dir/data.bin': DATA_BIN,
    }),
    exact: true,
  },
  {
    file: 'long.txt.Z',
    format: 'z',
    magic: [magic(0, [0x1f, 0x9d])],
    expected: () => ({ 'long.txt': LONG_TEXT }),
    exact: true,
  },
  {
    file: 'long.txt.lzma',
    format: 'lzma',
    magic: [magic(0, [0x5d, 0x00, 0x00])],
    expected: () => ({ 'long.txt': LONG_TEXT }),
    exact: true,
  },
];

function assertMagic(buffer: Buffer, expected: Magic): void {
  const start = expected.offset < 0 ? buffer.length + expected.offset : expected.offset;
  expect(buffer.subarray(start, start + expected.bytes.length)).toEqual(expected.bytes);
}

function expectFilesEqual(actual: Map<string, Buffer>, fixture: SourceFixture): void {
  const expected = fixture.expected();
  for (const [relPath, bytes] of Object.entries(expected)) {
    const found = actual.get(relPath);
    if (found === undefined) {
      throw new Error(`${fixture.file}: ${relPath} was not extracted; got ${JSON.stringify([...actual.keys()].sort())}`);
    }
    expect(found.equals(bytes), `${fixture.file}: bytes of ${relPath}`).toBe(true);
  }
  if (fixture.exact) {
    expect([...actual.keys()].sort()).toEqual(Object.keys(expected).sort());
  }
}

describe('7z listing key whitelist on every native archive source', () => {
  const sevenZip = getOracleToolPath('7z');
  const originalP7zipPath = process.env.P7ZIP_PATH;
  let workDir: string;

  beforeAll(() => {
    if (sevenZip) process.env.P7ZIP_PATH = sevenZip;
    workDir = fs.mkdtempSync(path.join(os.tmpdir(), 'easyconvert-archive-sources-'));
  });

  afterAll(() => {
    if (originalP7zipPath === undefined) {
      delete process.env.P7ZIP_PATH;
    } else {
      process.env.P7ZIP_PATH = originalP7zipPath;
    }
    fs.rmSync(workDir, { recursive: true, force: true });
  });

  it('keeps one fixture per format the registry and worker route to 7-Zip', () => {
    const covered = new Set(FIXTURES.map((fixture) => fixture.format));
    for (const format of ['iso', 'cab', 'arj', 'rpm', 'deb', 'cpio', 'dmg', 'img', 'lzma', 'z', 'lzh', 'wim']) {
      expect(covered.has(format), `no fixture for ${format}`).toBe(true);
    }
  });

  for (const fixture of FIXTURES) {
    it(`${fixture.file} is a genuine ${fixture.format} container`, () => {
      const buffer = readFixture(fixture.file);
      for (const expected of fixture.magic) assertMagic(buffer, expected);
    });

    oracleTest(
      `library route extracts ${fixture.file} (${fixture.format}) byte for byte`,
      ['7z'],
      async () => {
        const caseDir = fs.mkdtempSync(path.join(workDir, 'lib-'));
        const archivePath = path.join(caseDir, fixture.file);
        fs.copyFileSync(path.join(FIXTURE_DIR, fixture.file), archivePath);
        const extractDir = path.join(caseDir, 'out');
        fs.mkdirSync(extractDir);

        const tree = await extractArchiveContained({
          p7zBin: sevenZip!,
          archivePath,
          extractDir,
          cwd: caseDir,
          timeoutMs: EXTRACT_TIMEOUT_MS,
          maxBuffer: ARCHIVE_SECURITY_LIMITS.MAX_UNCOMPRESSED_SIZE,
          limits: ARCHIVE_SECURITY_LIMITS,
          label: `${fixture.format.toUpperCase()} archive`,
        });

        const actual = new Map(tree.files.map((file) => [file.relPath, fs.readFileSync(file.absPath)]));
        expectFilesEqual(actual, fixture);
        if (fixture.expectedEntryCount !== undefined) {
          expect(tree.entryCount).toBe(fixture.expectedEntryCount);
        }
      },
      SLOW_TEST_TIMEOUT_MS
    );

    if (fixture.workerFormat) {
      const workerFormat = fixture.workerFormat;
      oracleTest(
        `worker route converts ${fixture.file} (${workerFormat}) to a zip holding the same bytes`,
        ['7z'],
        async () => {
          const result = await convertWithNative7z(readFixture(fixture.file), workerFormat, 'zip', {}, fixture.file);
          if (result === null) throw new Error('worker route declined the archive');
          const zip = await JSZip.loadAsync(result.buffer);
          const actual = new Map<string, Buffer>();
          for (const [name, entry] of Object.entries(zip.files)) {
            if (!entry.dir) actual.set(name, await entry.async('nodebuffer'));
          }
          expectFilesEqual(actual, fixture);
        },
        SLOW_TEST_TIMEOUT_MS
      );
    }
  }
});

describe('RAR5 listing keys', () => {
  // 7-Zip prints `Copy Link` (the RAR5 file-copy reference) for every RAR5 entry; written by hand from a 23.01 listing.
  const RAR5_BLOCK = [
    'Path = a.txt',
    'Folder = -',
    'Size = 11',
    'Packed Size = 16',
    'Encrypted = +',
    'Host OS = Unix',
    'Method = m0:17 AES:15:1',
    'Symbolic Link = ',
    'Hard Link = ',
    'Copy Link = ',
    '',
  ].join('\n');

  it('accepts the Copy Link field and still reads the entry', () => {
    const [entry] = parse7zTechnicalListing(RAR5_BLOCK);
    expect(entry.path).toBe('a.txt');
    expect(entry.sizeBytes).toBe(11);
    expect(entry.linkKind).toBeNull();
  });
});

describe('the password prompt is not part of a listing', () => {
  const LISTING = 'Path = a.txt\nSize = 2\n';

  it.each([
    ['p7zip and 7-Zip up to 23.01', 'Enter password (will not be echoed):'],
    ['7-Zip 26.01', 'Enter password:'],
  ])('strips the %s prompt so the listing parses', (_build, prompt) => {
    const [entry] = parse7zTechnicalListing(stripSevenZipPasswordPrompt(`\n${prompt}\n${LISTING}`));
    expect(entry.path).toBe('a.txt');
    expect(entry.sizeBytes).toBe(2);
  });

  it('leaves a line that only starts like the prompt for the parser to refuse', () => {
    expect(() => parse7zTechnicalListing(stripSevenZipPasswordPrompt(`Enter passwords here\n${LISTING}`))).toThrow(
      /unrecognized line/
    );
  });
});
