import { describe, it, expect } from 'vitest';
import {
  computeOggCrc,
  createOggPage,
  encodeOpusContainer,
  encodeOggContainer,
  convertMedia,
} from '../src/lib/conversions/media';
import { decodeOgg } from '../src/lib/conversions/media-decoder';
import { EngineUnavailableError } from '../src/lib/types';
import { adtsStream, silentRawDataBlock } from './helpers/media-lossy-oracle';

function createSineWavBuffer(sampleRate: number, channels: number, durationSec: number): Buffer {
  const totalSamplesPerChannel = Math.floor(sampleRate * durationSec);
  const totalSamples = totalSamplesPerChannel * channels;
  const pcmBytes = totalSamples * 2;
  const header = Buffer.alloc(44);

  header.write('RIFF', 0);
  header.writeUInt32LE(36 + pcmBytes, 4);
  header.write('WAVE', 8);
  header.write('fmt ', 12);
  header.writeUInt32LE(16, 16); // PCM chunk size
  header.writeUInt16LE(1, 20); // Audio format: PCM
  header.writeUInt16LE(channels, 22);
  header.writeUInt32LE(sampleRate, 24);
  header.writeUInt32LE(sampleRate * channels * 2, 28); // Byte rate
  header.writeUInt16LE(channels * 2, 32); // Block align
  header.writeUInt16LE(16, 34); // Bits per sample
  header.write('data', 36);
  header.writeUInt32LE(pcmBytes, 40);

  const data = Buffer.alloc(pcmBytes);
  const freq = 440.0;
  for (let i = 0; i < totalSamplesPerChannel; i++) {
    const t = i / sampleRate;
    const sample = Math.round(Math.sin(2 * Math.PI * freq * t) * 12000);
    for (let c = 0; c < channels; c++) {
      data.writeInt16LE(sample, (i * channels + c) * 2);
    }
  }

  return Buffer.concat([header, data]);
}

describe('Phase 3: Pure TypeScript Codecs Parity (RFC 7845 Ogg Bitstream)', () => {
  // ==========================================================================
  // 1. AAC needs the FFmpeg engine (no in-process encoder or decoder)
  // ==========================================================================
  describe('1. AAC needs the FFmpeg engine', () => {
    it('refuses to encode or decode AAC without the native engine', async () => {
      const wav = createSineWavBuffer(44100, 2, 0.25);
      const encodeError = await convertMedia(
        wav,
        'wav',
        'aac',
        { disableNativeEngine: true },
        'audio.wav'
      ).catch((err: unknown) => err);
      expect(encodeError).toBeInstanceOf(EngineUnavailableError);

      const adts = adtsStream(new Array(4).fill(silentRawDataBlock(2)), 44100, 2);
      // ADTS header fields: MPEG-4, layer 0, protection absent; AAC LC; 44.1 kHz = index 4
      expect(adts[1] & 0x0f).toBe(0x01);
      expect((adts[2] >> 6) & 0x03).toBe(1);
      expect((adts[2] >> 2) & 0x0f).toBe(4);

      const decodeError = await convertMedia(adts, 'aac', 'wav', { disableNativeEngine: true }, 'audio.aac').catch(
        (err: unknown) => err
      );
      expect(decodeError).toBeInstanceOf(EngineUnavailableError);
      expect((decodeError as EngineUnavailableError).engineName).toBe('ffmpeg');
    });
  });

  // ==========================================================================
  // 2. RFC 3533 Ogg Page Checksum (0x04C11DB7) & Page Framing
  // ==========================================================================
  describe('2. RFC 3533 Ogg CRC-32 Generator Polynomial (0x04C11DB7)', () => {
    it('computes exact RFC 3533 32-bit CRC checksum matching polynomial 0x04C11DB7', () => {
      // Direct calculation on standard test vectors
      const testBuffer = Buffer.from('OggS');
      const crc = computeOggCrc(testBuffer);
      expect(crc).toBe(0x5fb0a94f);

      // Verify that all pages generated by createOggPage have valid non-zero CRC-32
      const payload = Buffer.from('TEST_OGG_PAYLOAD_STRING_12345');
      const page = createOggPage(payload, 0x02, 0, 1, 0x12345678);

      expect(page.toString('ascii', 0, 4)).toBe('OggS');
      const storedCrc = page.readUInt32LE(22);
      expect(storedCrc).not.toBe(0);

      // Verify self-consistency: zeroing bytes 22-25 and recalculating CRC must yield storedCrc
      const pageCopy = Buffer.from(page);
      pageCopy.writeUInt32LE(0, 22);
      const recomputedCrc = computeOggCrc(pageCopy);
      expect(recomputedCrc).toBe(storedCrc);
    });

    it('detects any byte alteration in header or payload via CRC divergence', () => {
      const payload = Buffer.from('AUTHENTIC_PAYLOAD_DATA');
      const page = createOggPage(payload, 0x00, 1000, 2, 0x12345678);
      const expectedCrc = page.readUInt32LE(22);

      // Tamper with payload byte
      const tampered = Buffer.from(page);
      tampered[tampered.length - 1] ^= 0x01;
      tampered.writeUInt32LE(0, 22);
      const tamperedCrc = computeOggCrc(tampered);

      expect(tamperedCrc).not.toBe(expectedCrc);
    });

    it('handles segment table segmentation and limit boundaries (> 255 bytes)', () => {
      const largePayload = Buffer.alloc(1000, 0xaa);
      const page = createOggPage(largePayload, 0x00, 2000, 3, 0x12345678);

      const segCount = page[26];
      // 1000 = 3 * 255 + 235 => 4 segments
      expect(segCount).toBe(4);
      expect(page[27]).toBe(255);
      expect(page[28]).toBe(255);
      expect(page[29]).toBe(255);
      expect(page[30]).toBe(235);

      const headerLen = 27 + segCount;
      expect(page.length).toBe(headerLen + 1000);
      expect(page.readUInt32LE(22)).not.toBe(0);
    });
  });

  // ==========================================================================
  // 3. RFC 7845 Ogg Opus & RFC 6716 TOC Byte Framing
  // ==========================================================================
  describe('3. RFC 7845 Ogg Opus Container & RFC 6716 TOC Framing', () => {
    it('creates RFC 7845 compliant OpusHead (BOS) and OpusTags pages with valid CRCs', () => {
      const packets = [Buffer.from([0xc4, 0x01, 0x02, 0x03]), Buffer.from([0xc4, 0x04, 0x05, 0x06])];

      const oggOpus = encodeOpusContainer(packets, 48000, 2, 'Test Song');
      expect(oggOpus.toString('ascii', 0, 4)).toBe('OggS');

      // Verify Page 1: OpusHead
      expect(oggOpus[5]).toBe(0x02); // BOS flag
      expect(oggOpus.readBigInt64LE(6)).toBe(0n); // Granule = 0
      expect(oggOpus.readUInt32LE(18)).toBe(1); // Sequence = 1
      const p1Crc = oggOpus.readUInt32LE(22);
      expect(p1Crc).not.toBe(0);

      const headIdx = oggOpus.indexOf('OpusHead');
      expect(headIdx).toBeGreaterThan(0);
      expect(oggOpus.readUInt8(headIdx + 8)).toBe(1); // Version 1
      expect(oggOpus.readUInt8(headIdx + 9)).toBe(2); // 2 channels
      expect(oggOpus.readUInt16LE(headIdx + 10)).toBe(384); // Pre-skip 384
      expect(oggOpus.readUInt32LE(headIdx + 12)).toBe(48000); // 48kHz

      // Verify Page 2: OpusTags
      const tagsIdx = oggOpus.indexOf('OpusTags');
      expect(tagsIdx).toBeGreaterThan(headIdx);
      expect(oggOpus.indexOf('EasyConvert Engine')).toBeGreaterThan(tagsIdx);

      // Verify Fail-Closed on raw PCM Int16Array
      expect(() => encodeOpusContainer(new Int16Array(960 * 2), 48000, 2)).toThrow(
        /Authentic Opus bitstream encoder is required/i
      );
    });

    it('packages discrete Opus audio packets with RFC 6716 TOC byte structure (0xC0 mono, 0xC4 stereo)', () => {
      // Stereo: TOC = 0xC4
      const stereoPackets = [Buffer.from([0xc4, 0x10, 0x20, 0x30]), Buffer.from([0xc4, 0x40, 0x50, 0x60])];
      const stereoOgg = encodeOpusContainer(stereoPackets, 48000, 2, 'Stereo');

      // Find third OggS page (first audio page)
      let offset = 0;
      let pageCount = 0;
      let audioPageOffset = -1;
      while (offset + 27 <= stereoOgg.length) {
        if (stereoOgg.toString('ascii', offset, offset + 4) === 'OggS') {
          pageCount++;
          if (pageCount === 3) {
            audioPageOffset = offset;
            break;
          }
          const segCount = stereoOgg[offset + 26];
          let payloadLen = 0;
          for (let s = 0; s < segCount; s++) payloadLen += stereoOgg[offset + 27 + s];
          offset += 27 + segCount + payloadLen;
        } else {
          offset++;
        }
      }

      expect(audioPageOffset).toBeGreaterThan(0);
      const segCount = stereoOgg[audioPageOffset + 26];
      const payloadStart = audioPageOffset + 27 + segCount;
      const tocByteStereo = stereoOgg[payloadStart];
      expect(tocByteStereo).toBe(0xc4); // Config 24 CELT 20ms + Stereo flag 0x04

      // Mono: TOC = 0xC0
      const monoPackets = [Buffer.from([0xc0, 0x10, 0x20, 0x30]), Buffer.from([0xc0, 0x40, 0x50, 0x60])];
      const monoOgg = encodeOpusContainer(monoPackets, 48000, 1, 'Mono');

      offset = 0;
      pageCount = 0;
      audioPageOffset = -1;
      while (offset + 27 <= monoOgg.length) {
        if (monoOgg.toString('ascii', offset, offset + 4) === 'OggS') {
          pageCount++;
          if (pageCount === 3) {
            audioPageOffset = offset;
            break;
          }
          const segCount = monoOgg[offset + 26];
          let payloadLen = 0;
          for (let s = 0; s < segCount; s++) payloadLen += monoOgg[offset + 27 + s];
          offset += 27 + segCount + payloadLen;
        } else {
          offset++;
        }
      }

      expect(audioPageOffset).toBeGreaterThan(0);
      const segCountMono = monoOgg[audioPageOffset + 26];
      const payloadStartMono = audioPageOffset + 27 + segCountMono;
      const tocByteMono = monoOgg[payloadStartMono];
      expect(tocByteMono).toBe(0xc0); // Config 24 CELT 20ms + Mono
    });

    it('enforces Fail-Closed for pure TS WAV -> OPUS without native FFmpeg engine', async () => {
      const wav = createSineWavBuffer(48000, 2, 0.2);
      await expect(
        convertMedia(wav, 'wav', 'opus', { disableNativeEngine: true }, 'test.wav')
      ).rejects.toThrow(/Native FFmpeg engine is required for authentic lossy OPUS compression/i);
    });
  });

  // ==========================================================================
  // 4. RFC 3533 Ogg Vorbis Header Triad & Discrete Audio Framing
  // ==========================================================================
  describe('4. RFC 3533 Ogg Vorbis Header Triad & Discrete Audio Framing', () => {
    it('encodes all 3 mandatory Vorbis headers (Identification, Comments, Setup) in order', () => {
      const packets = [Buffer.from([0x00, 0x11, 0x22]), Buffer.from([0x00, 0x33, 0x44])];

      const oggVorbis = encodeOggContainer(packets, 44100, 2, 'Vorbis Song');

      // Verify all 3 headers are present
      const idIdx = oggVorbis.indexOf(Buffer.from([0x01, 0x76, 0x6f, 0x72, 0x62, 0x69, 0x73]));
      const commentIdx = oggVorbis.indexOf(Buffer.from([0x03, 0x76, 0x6f, 0x72, 0x62, 0x69, 0x73]));
      const setupIdx = oggVorbis.indexOf(Buffer.from([0x05, 0x76, 0x6f, 0x72, 0x62, 0x69, 0x73]));

      expect(idIdx).toBeGreaterThan(0);
      expect(commentIdx).toBeGreaterThan(idIdx);
      expect(setupIdx).toBeGreaterThan(commentIdx);

      // Verify setup header codebook magic 'BCV' (0x564342)
      expect(oggVorbis.indexOf(Buffer.from([0x42, 0x43, 0x56]))).toBeGreaterThan(setupIdx);

      // Verify Fail-Closed on raw PCM Int16Array
      expect(() => encodeOggContainer(new Int16Array(1024), 44100, 2)).toThrow(
        /Authentic Vorbis bitstream encoder is required/i
      );
    });

    it('enforces Fail-Closed for pure TS WAV -> OGG (Vorbis) without native FFmpeg engine', async () => {
      const wav = createSineWavBuffer(44100, 2, 0.2);
      await expect(
        convertMedia(wav, 'wav', 'ogg', { disableNativeEngine: true }, 'vorbis.wav')
      ).rejects.toThrow(/Native FFmpeg engine is required for authentic lossy OGG compression/i);
    });
  });

  // ==========================================================================
  // 5. Negative & Boundary Fuzzing (Fail-Closed)
  // ==========================================================================
  describe('5. Negative & Boundary Fuzzing (Fail-Closed)', () => {
    it('handles 0-packet empty audio buffers gracefully without crashing and decodes to 0-length PCM', () => {
      const empty: Buffer[] = [];
      const opusOgg = encodeOpusContainer(empty, 48000, 2, 'Empty');
      expect(opusOgg.length).toBeGreaterThan(0);
      expect(opusOgg.toString('ascii', 0, 4)).toBe('OggS');

      const decOpus = decodeOgg(opusOgg);
      expect(decOpus.samples.length).toBe(0);
      expect(decOpus.duration).toBe(0);
      expect(decOpus.channels).toBe(2);

      const vorbisOgg = encodeOggContainer(empty, 44100, 2, 'Empty');
      expect(vorbisOgg.length).toBeGreaterThan(0);
      expect(vorbisOgg.toString('ascii', 0, 4)).toBe('OggS');

      const decVorbis = decodeOgg(vorbisOgg);
      expect(decVorbis.samples.length).toBe(0);
      expect(decVorbis.duration).toBe(0);
      expect(decVorbis.channels).toBe(2);
    });

    it('fails closed when decoding severely truncated or corrupt Ogg headers', () => {
      const truncated = Buffer.from([0x4f, 0x67, 0x67, 0x53, 0x00, 0x02]); // 'OggS' only 6 bytes
      expect(() => decodeOgg(truncated)).toThrow(/Unsupported audio format/i);
    });

    it('fails closed on unknown container streams lacking OggS sync markers', () => {
      const garbage = Buffer.from('RANDOM_CORRUPT_DATA_STRING_FOR_AUDIO_TESTING');
      expect(() => decodeOgg(garbage)).toThrow(/Unsupported audio format/i);
    });

    it('rejects multi-channel audio (> 2 channels) and invalid channels with fail-closed errors', () => {
      const packets = [Buffer.from([0xc0, 0x01, 0x02])];
      expect(() => encodeOpusContainer(packets, 48000, 6, 'surround')).toThrow(/Unsupported channel configuration for Ogg Opus/i);
      expect(() => encodeOpusContainer(packets, 48000, 0, 'invalid')).toThrow(/Unsupported channel configuration for Ogg Opus/i);
      expect(() => encodeOggContainer(packets, 44100, 6, 'surround')).toThrow(/Unsupported channel configuration for Ogg Vorbis/i);
      expect(() => encodeOggContainer(packets, 44100, 0, 'invalid')).toThrow(/Unsupported channel configuration for Ogg Vorbis/i);
    });
  });
});
