import { describe, it, expect } from 'vitest';
import crypto from 'node:crypto';
import JSZip from 'jszip';
import { convertVectorCad, parseCgmToSvg } from '../src/lib/conversions/vector-cad';
import { convertOffice, extractTextContentForOffice } from '../src/lib/conversions/office';
import { create7zArchive, extract7zArchive } from '../src/lib/conversions/archive';
import { convertMedia, ConversionFailedError, checkFfmpeg } from '../src/lib/conversions/media';
import { EngineUnavailableError } from '../src/lib/types';
import {
  applyRgbaQuantize,
  WasmEngine,
} from '../src/lib/edge/workers/wasm-engine.worker';
import { executeWasmTask, WasmWorkerManager } from '../src/lib/edge/pipelines/wasm-simd-pipeline';

describe('Phase 1: Fail-Closed Principle, L2 Wasm Color Integrity & 7z Multi-file Extraction', () => {
  // ==========================================================================
  // Gate 1: Vector/CAD Fail-Closed Integrity & Removal of Dummy SVGs
  // ==========================================================================
  describe('Gate 1: Vector/CAD Fail-Closed Integrity', () => {
    it('fails closed on unsupported binary vector formats instead of generating dummy purple SVGs', async () => {
      const mockBinaryCdr = Buffer.from([0xd0, 0xcf, 0x11, 0xe0, 0x00, 0x01, 0x02, 0x03]);

      await expect(
        convertVectorCad(mockBinaryCdr, 'cdr', 'svg', {}, 'design.cdr')
      ).rejects.toThrow(/Unsupported or unparseable \.cdr vector format/);

      await expect(
        convertVectorCad(mockBinaryCdr, 'wmf', 'svg', {}, 'sketch.wmf')
      ).rejects.toThrow(/Unsupported or unparseable \.wmf vector format/);

      await expect(
        convertVectorCad(mockBinaryCdr, 'emf', 'png', {}, 'layout.emf')
      ).rejects.toThrow(/Unsupported or unparseable \.emf vector format/);

      await expect(
        convertVectorCad(mockBinaryCdr, 'dwf', 'svg', {}, 'blueprint.dwf')
      ).rejects.toThrow(/Unsupported or unparseable \.dwf vector format/);

      await expect(
        convertVectorCad(mockBinaryCdr, 'vsd', 'svg', {}, 'diagram.vsd')
      ).rejects.toThrow(/Unsupported or unparseable \.vsd vector format/);
    });

    it('parses genuine CGM commands into real SVG elements without dummy templates', async () => {
      const cgmText = `BEGMF "authentic-drawing";
MFVERSION 1;
MFDESC "Generated by EasyConvert Vector Engine";
MFELEMENTLIST "DRAWINGSET";
BEGMFDEFAULTS;
ENDMFDEFAULTS;
BEGPIC "picture 1";
BEGPICBODY;
VDCEXT (0,0) (800,600);
LINE (10,10) (790,10);
LINE (790,10) (790,590);
LINE (790,590) (10,590);
LINE (10,590) (10,10);
TEXT (40,300) final "Vector Graphic: authentic-drawing";
ENDPIC;
ENDMF;
`;
      const cgmData = Buffer.from(cgmText, 'utf-8');
      const res = await convertVectorCad(cgmData, 'cgm', 'svg', {}, 'authentic-drawing.cgm');

      expect(res.filename).toBe('authentic-drawing.svg');
      expect(res.mimeType).toBe('image/svg+xml');
      const svgText = res.buffer.toString('utf-8');

      // Must contain real CGM elements (LINE, TEXT) and viewbox
      expect(svgText).toContain('<svg');
      expect(svgText).toContain('<line');
      expect(svgText).toContain('authentic-drawing');

      // Must NEVER contain the dummy placeholder path or lavender signature
      expect(svgText).not.toContain('#6366f1');
      expect(svgText).not.toContain('M 80 180');
      expect(svgText).not.toContain('stroke-dasharray="6 4"');
    });

    it('fails closed when CGM input contains arbitrary non-CGM text', async () => {
      const badCgm = Buffer.from('NOT_A_CGM_FILE_RANDOM_GARBAGE');
      await expect(
        convertVectorCad(badCgm, 'cgm', 'svg', {}, 'corrupted.cgm')
      ).rejects.toThrow(/Unsupported or unparseable \.cgm vector format/);
    });
  });

  // ==========================================================================
  // Gate 2: Office Fail-Closed Protection Against Silent Mojibake Corruption
  // ==========================================================================
  describe('Gate 2: Office Fail-Closed Text Extraction', () => {
    it('rejects unsupported binary/compressed container formats (pages, numbers, epub, pub, lwp)', async () => {
      // Mock Apple Pages ZIP archive
      const zip = new JSZip();
      zip.file('Index/Document.iwa', Buffer.from([0x00, 0x11, 0x22, 0x33]));
      const pagesBuffer = await zip.generateAsync({ type: 'nodebuffer' });

      // pages -> docx must reject fail-closed instead of packing mojibake into docx
      await expect(
        convertOffice(pagesBuffer, 'pages', 'docx', {}, 'notes.pages')
      ).rejects.toThrow(/Unsupported binary or compressed format '\.pages'/);

      // numbers -> docx must reject fail-closed
      await expect(
        convertOffice(pagesBuffer, 'numbers', 'docx', {}, 'sheet.numbers')
      ).rejects.toThrow(/Unsupported binary or compressed format '\.numbers'/);

      // extractTextContentForOffice must reject epub/pages/numbers directly to prevent mojibake corruption
      await expect(
        extractTextContentForOffice(pagesBuffer, 'epub', {}, 'book.epub')
      ).rejects.toThrow(/Unsupported binary or compressed format '\.epub'/);

      await expect(
        extractTextContentForOffice(pagesBuffer, 'pages', {}, 'doc.pages')
      ).rejects.toThrow(/Unsupported binary or compressed format '\.pages'/);
    });

    it('rejects binary CFBF/OLE2 documents (pub, lwp) with null bytes', async () => {
      const pubMock = Buffer.concat([
        Buffer.from([0xd0, 0xcf, 0x11, 0xe0]),
        Buffer.from('Microsoft Publisher 2000 Document\0\0\0\x05\x00'),
        crypto.randomBytes(64),
      ]);

      await expect(
        convertOffice(pubMock, 'pub', 'docx', {}, 'flyer.pub')
      ).rejects.toThrow(/fail-closed against mojibake corruption/);

      await expect(
        convertOffice(pubMock, 'lwp', 'docx', {}, 'memo.lwp')
      ).rejects.toThrow(/fail-closed against mojibake corruption/);
    });

    it('allows clean UTF-8 text formats (txt, md, csv) to convert normally', async () => {
      const mdBuffer = Buffer.from('# Executive Report\n\nAll metrics are verified.', 'utf-8');
      const res = await convertOffice(mdBuffer, 'md', 'docx', {}, 'report.md');
      expect(res.mimeType).toBe(
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
      );
      expect(res.buffer.length).toBeGreaterThan(0);
    });
  });

  // ==========================================================================
  // Gate 3: L2 Wasm Color Integrity & Quantization
  // ==========================================================================
  describe('Gate 3: L2 Wasm Color Integrity', () => {
    it('preserves chromatic RGB channels and prevents forced grayscale under palette quantization', () => {
      // 4 pixels: Pure Red, Pure Green, Pure Blue, Pure Yellow
      const input = new Uint8Array([
        255, 0, 0, 255,       // Red
        0, 255, 0, 255,       // Green
        0, 0, 255, 255,       // Blue
        255, 255, 0, 255,     // Yellow
      ]);

      const quantized = applyRgbaQuantize(input, 4, 1, 256, false);
      expect(quantized).toHaveLength(16);

      // Red pixel: Red channel MUST be vibrant, NOT grayscale (76, 76, 76)
      expect(quantized[0]).toBe(255);
      expect(quantized[1]).toBe(0);
      expect(quantized[2]).toBe(0);
      expect(quantized[3]).toBe(255);

      // Green pixel: Green channel MUST be vibrant, NOT grayscale (149, 149, 149)
      expect(quantized[4]).toBe(0);
      expect(quantized[5]).toBe(255);
      expect(quantized[6]).toBe(0);
      expect(quantized[7]).toBe(255);

      // Blue pixel: Blue channel MUST be vibrant, NOT grayscale (28, 28, 28)
      expect(quantized[8]).toBe(0);
      expect(quantized[9]).toBe(0);
      expect(quantized[10]).toBe(255);
      expect(quantized[11]).toBe(255);

      // Yellow pixel: Red + Green vibrant, Blue zero
      expect(quantized[12]).toBe(255);
      expect(quantized[13]).toBe(255);
      expect(quantized[14]).toBe(0);
      expect(quantized[15]).toBe(255);
    });

    it('applies Floyd-Steinberg error diffusion dithering when dither option is active', () => {
      const gradient = new Uint8Array([
        100, 150, 200, 255,
        110, 160, 210, 255,
        120, 170, 220, 255,
        130, 180, 230, 255,
      ]);

      const dithered = applyRgbaQuantize(gradient, 2, 2, 64, true);
      expect(dithered).toHaveLength(16);
      // Dithered pixels should have non-zero chromatic color values
      expect(dithered[0]).toBeGreaterThan(0);
      expect(dithered[1]).toBeGreaterThan(0);
      expect(dithered[2]).toBeGreaterThan(0);
      expect(dithered[3]).toBe(255);
    });

    it('executes rgba-quantize task through WasmWorkerManager', async () => {
      const input = new Uint8Array([255, 0, 0, 255, 0, 255, 0, 255]).buffer;
      const res = await executeWasmTask('rgba-quantize', input, {
        width: 2,
        height: 1,
        colors: 256,
        palette: true,
      });

      expect(res.bytesProcessed).toBe(8);
      const out = new Uint8Array(res.buffer);
      // Colors must be preserved
      expect(out[0]).toBe(255);
      expect(out[5]).toBe(255);
    });
  });

  // ==========================================================================
  // Gate 4: 7z Archive Multi-File Extraction Integrity
  // ==========================================================================
  describe('Gate 4: 7z Archive Multi-File Extraction Integrity', () => {
    it('extracts distinct byte buffers for each file without duplicate slice assignment', () => {
      const file1 = {
        filename: 'document.txt',
        buffer: Buffer.from('First file content: ' + crypto.randomUUID()),
      };
      const file2 = {
        filename: 'data.json',
        buffer: Buffer.from(JSON.stringify({ service: 'EasyConvert', version: '2026.1', secure: true })),
      };
      const file3 = {
        filename: 'binary.dat',
        buffer: crypto.randomBytes(64),
      };

      // 1. Pack into 7z
      const archiveResult = create7zArchive([file1, file2, file3], {}, 'bundle.7z');
      expect(archiveResult.mimeType).toBe('application/x-7z-compressed');
      expect(archiveResult.buffer.length).toBeGreaterThan(32);

      // 2. Extract files
      const extracted = extract7zArchive(archiveResult.buffer);

      expect(extracted).toHaveLength(3);

      // Verify file 1
      expect(extracted[0].filename).toBe('document.txt');
      expect(extracted[0].buffer.equals(file1.buffer)).toBe(true);
      expect(
        crypto.createHash('sha256').update(extracted[0].buffer).digest('hex')
      ).toBe(
        crypto.createHash('sha256').update(file1.buffer).digest('hex')
      );

      // Verify file 2
      expect(extracted[1].filename).toBe('data.json');
      expect(extracted[1].buffer.equals(file2.buffer)).toBe(true);
      expect(
        crypto.createHash('sha256').update(extracted[1].buffer).digest('hex')
      ).toBe(
        crypto.createHash('sha256').update(file2.buffer).digest('hex')
      );

      // Verify file 3
      expect(extracted[2].filename).toBe('binary.dat');
      expect(extracted[2].buffer.equals(file3.buffer)).toBe(true);
      expect(
        crypto.createHash('sha256').update(extracted[2].buffer).digest('hex')
      ).toBe(
        crypto.createHash('sha256').update(file3.buffer).digest('hex')
      );

      // Critical check: buffers must NOT be identical in content across files
      expect(extracted[0].buffer.equals(extracted[1].buffer)).toBe(false);
      expect(extracted[1].buffer.equals(extracted[2].buffer)).toBe(false);
    });

    it('correctly extracts single file 7z archives without regression', () => {
      const singleFile = {
        filename: 'solo.txt',
        buffer: Buffer.from('Solo payload for single file test'),
      };

      const archive = create7zArchive([singleFile], {}, 'solo.7z');
      const extracted = extract7zArchive(archive.buffer);

      expect(extracted).toHaveLength(1);
      expect(extracted[0].filename).toBe('solo.txt');
      expect(extracted[0].buffer.toString('utf-8')).toBe('Solo payload for single file test');
    });
  });

  // ==========================================================================
  // Gate 6: Media Fail-Closed Enforcement for Lossy Psychoacoustic Codecs
  // ==========================================================================
  describe('Gate 6: Media Fail-Closed Enforcement Without Native FFmpeg', () => {
    function createTestWav(): Buffer {
      const sampleRate = 44100;
      const channels = 2;
      const samples = 4410;
      const dataSize = samples * 2 * channels;
      const buf = Buffer.alloc(44 + dataSize);
      buf.write('RIFF', 0);
      buf.writeUInt32LE(36 + dataSize, 4);
      buf.write('WAVE', 8);
      buf.write('fmt ', 12);
      buf.writeUInt32LE(16, 16);
      buf.writeUInt16LE(1, 20);
      buf.writeUInt16LE(channels, 22);
      buf.writeUInt32LE(sampleRate, 24);
      buf.writeUInt32LE(sampleRate * channels * 2, 28);
      buf.writeUInt16LE(channels * 2, 32);
      buf.writeUInt16LE(16, 34);
      buf.write('data', 36);
      buf.writeUInt32LE(dataSize, 40);
      return buf;
    }

    it('strictly throws ConversionFailedError for lossy psychoacoustic formats when FFmpeg is absent or disabled', async () => {
      const wav = createTestWav();

      await expect(
        convertMedia(wav, 'wav', 'opus', { disableNativeEngine: true }, 'test.wav')
      ).rejects.toThrow(ConversionFailedError);
      await expect(
        convertMedia(wav, 'wav', 'ogg', { disableNativeEngine: true }, 'test.wav')
      ).rejects.toThrow(ConversionFailedError);
      await expect(
        convertMedia(wav, 'wav', 'aac', { disableNativeEngine: true }, 'test.wav')
      ).rejects.toThrow(ConversionFailedError);
      await expect(
        convertMedia(wav, 'wav', 'mp4', { disableNativeEngine: true }, 'test.wav')
      ).rejects.toThrow(ConversionFailedError);
      await expect(
        convertMedia(wav, 'wav', 'mp3', { disableNativeEngine: true }, 'test.wav')
      ).rejects.toThrow(ConversionFailedError);
    });

    it('allows lossless FLAC without the native engine but refuses pure MP3 even with allowPureLossyBitstream', async () => {
      const wav = createTestWav();

      const flacRes = await convertMedia(wav, 'wav', 'flac', { disableNativeEngine: true }, 'test.wav');
      expect(flacRes.mimeType).toBe('audio/flac');
      expect(flacRes.buffer.indexOf('fLaC')).toBe(0);

      const mp3Error = await convertMedia(
        wav,
        'wav',
        'mp3',
        { disableNativeEngine: true, allowPureLossyBitstream: true },
        'test.wav'
      ).catch((err: unknown) => err);
      expect(mp3Error).toBeInstanceOf(EngineUnavailableError);
      expect((mp3Error as EngineUnavailableError).engineName).toBe('ffmpeg');
    });
  });

});


