/**
 * Pure Isomorphic CAD Converter (Level 0 Fast-Path)
 *
 * Standalone mathematical STEP/IGES to STL/OBJ tessellation using TextDecoder
 * and pure typed arrays (strictly zero sharp, pdfkit, or vector-cad.ts imports).
 */

import { tessellateCadText, TessellatedMesh } from '../../conversions/cad-nurbs';

export interface PureCadResult {
  data: Uint8Array;
  text: string;
  mimeType: string;
  extension: string;
}

const SUPPORTED_CAD_SOURCES = new Set(['step', 'stp', 'iges', 'igs']);
const SUPPORTED_CAD_TARGETS = new Set(['stl', 'obj']);

const CAD_MIME_MAP: Record<string, string> = {
  stl: 'model/stl',
  obj: 'model/obj',
};

/**
 * Checks whether the source and target formats are supported by the pure CAD engine.
 */
export function isPureCadConvertible(sourceFormat: string, targetFormat: string): boolean {
  const src = sourceFormat.toLowerCase();
  const tgt = targetFormat.toLowerCase();
  return SUPPORTED_CAD_SOURCES.has(src) && SUPPORTED_CAD_TARGETS.has(tgt);
}

/**
 * Encodes 3D TessellatedMesh to ASCII Stereolithography (STL) format.
 */
export function encodeStl(mesh: TessellatedMesh): string {
  let stl = `solid ${mesh.name || 'EasyConvert_Model'}\n`;

  mesh.faces.forEach((face) => {
    const v1 = mesh.vertices[face[0]] || [0, 0, 0];
    const v2 = mesh.vertices[face[1]] || [0, 0, 0];
    const v3 = mesh.vertices[face[2]] || [0, 0, 0];

    const ax = v2[0] - v1[0];
    const ay = v2[1] - v1[1];
    const az = v2[2] - v1[2];
    const bx = v3[0] - v1[0];
    const by = v3[1] - v1[1];
    const bz = v3[2] - v1[2];

    const nx = ay * bz - az * by;
    const ny = az * bx - ax * bz;
    const nz = ax * by - ay * bx;
    const len = Math.hypot(nx, ny, nz) || 1;

    stl += `  facet normal ${nx / len} ${ny / len} ${nz / len}\n`;
    stl += `    outer loop\n`;
    stl += `      vertex ${v1[0]} ${v1[1]} ${v1[2]}\n`;
    stl += `      vertex ${v2[0]} ${v2[1]} ${v2[2]}\n`;
    stl += `      vertex ${v3[0]} ${v3[1]} ${v3[2]}\n`;
    stl += `    endloop\n`;
    stl += `  endfacet\n`;
  });

  stl += `endsolid ${mesh.name || 'EasyConvert_Model'}\n`;
  return stl;
}

/**
 * Encodes 3D TessellatedMesh to Wavefront OBJ format.
 */
export function encodeObj(mesh: TessellatedMesh): string {
  let obj = `# Wavefront OBJ generated by EasyConvert Pure Engine\no ${mesh.name || 'model'}\n\n`;

  mesh.vertices.forEach((v) => {
    obj += `v ${v[0]} ${v[1]} ${v[2]}\n`;
  });

  if (mesh.normals && mesh.normals.length === mesh.vertices.length) {
    obj += '\n';
    mesh.normals.forEach((n) => {
      obj += `vn ${n[0]} ${n[1]} ${n[2]}\n`;
    });
  }

  obj += '\n';

  mesh.faces.forEach((f) => {
    if (mesh.normals && mesh.normals.length === mesh.vertices.length) {
      obj += `f ${f[0] + 1}//${f[0] + 1} ${f[1] + 1}//${f[1] + 1} ${f[2] + 1}//${f[2] + 1}\n`;
    } else {
      obj += `f ${f[0] + 1} ${f[1] + 1} ${f[2] + 1}\n`;
    }
  });

  return obj;
}

/**
 * Converts STEP/IGES CAD model into 3D mesh (STL or OBJ) purely in-memory.
 */
export function convertPureCad(
  input: string | Uint8Array,
  sourceFormat: string,
  targetFormat: string,
  modelName = 'cad_model'
): PureCadResult {
  const src = sourceFormat.toLowerCase();
  const tgt = targetFormat.toLowerCase();

  if (!isPureCadConvertible(src, tgt)) {
    throw new Error(`Pure CAD engine does not support conversion from '${src}' to '${tgt}'.`);
  }

  const textContent =
    typeof input === 'string' ? input : new TextDecoder('utf-8').decode(input);

  const mesh = tessellateCadText(textContent, src, modelName);

  let outputText = '';
  if (tgt === 'stl') {
    outputText = encodeStl(mesh);
  } else if (tgt === 'obj') {
    outputText = encodeObj(mesh);
  } else {
    throw new Error(`Unsupported target CAD format: ${tgt}`);
  }

  const encoder = new TextEncoder();
  const data = encoder.encode(outputText);
  const mimeType = CAD_MIME_MAP[tgt] || 'application/octet-stream';

  return {
    data,
    text: outputText,
    mimeType,
    extension: tgt,
  };
}
